version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  lint:
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run linter
          command: yarn lint
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor:
      name: node/default
      tag: lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test:ci

workflows:
  lint-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
