require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

abstract_target 'RNTemplate' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'Development' do
    # Development-specific pods
  end

  target 'Production' do
    # Production-specific pods
  end

  target 'Staging' do
    # Staging-specific pods
  end

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.132.0' })
  end

  post_install do |installer|
    react_native_post_install(installer)

    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
